background_opacity 0.85
dynamic_background_opacity yes

hide_window_decorations yes
tab_bar_style hidden

background #11151c
foreground #d8dee9
cursor #3f76e6
cursor_text_color #11151c

selection_background #3c527f
selection_foreground #11151c

url_color #3f76e6

color0  #1c2129
color8  #4b5563
color1  #d16969
color9  #e08585
color2  #7fae5c
color10 #9bc97e
color3  #cf9d4f
color11 #e0b876
color4  #3f76e6
color12 #6f9ce8
color5  #935b2a
color13 #b06a2c
color6  #5fb3b3
color14 #7fcaca
color7  #d8dee9
color15 #ffffff

copy_on_select clipboard
strip_trailing_spaces smart
